source "https://api.berkshelf.com"

cookbook 'apache2', '~> 5.0.1'
cookbook 'apt', '~> 6.1.4'
cookbook 'iptables', '~> 4.2.1'
cookbook 'logrotate', '~> 2.2.0'
cookbook 'mariadb', '~> 1.5.2'
cookbook 'openssl', '~> 7.1.0'
